[package]
name = "stonehearth_2"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
env_logger = "0.9.1"
log = "0.4.17"
winit = "0.27.4"
wgpu = "0.14.0"
pollster = "0.2.5"
bytemuck = { version = "1.12.1", features = ["derive"] }
cgmath = "0.18"
